### ISSUE TITLE
Ran capec but zero triples added

### ISSUE THREAD

**Issue by Radu3000** [sepses/cyber-kg-converter#1]
After running this command:
- un java -jar target/cyber-kb-<version>-jar-with-dependencies.jar -p capec

I am getting zero triples in fuseki.

2020-02-07 11:43:28 INFO  CAPECParser - Store data to http://localhost:3030/sepses using graph http://w3id.org/sepses/graph/capec
2020-02-07 11:43:28 INFO  DummyStorage - Do nothing
2020-02-07 11:43:28 INFO  MainParser - ************* CAPEC parser finished
2020-02-07 11:43:28 INFO  MainParser - Transformation process finished in 4732 milliseconds

I suspect that it has something to do with this comment:
- "you can also run it without storing the data to triplestore using "dummy" as storage"
- "currently still need an active sparql endpoint (TODO: to fix this)."

Please let me know what needs to be done.

Thank you,
Radu

**Comment by Radu3000** [comment]
Never mind - the with this setting:
- Triplestore=dummy

I get what I need:
- 1000.xml.zip-output.ttl in the output directory

**Comment by fekaputra** [comment]
Hi Radu, 

it’s a matter of configuration (config.properties need to be adjusted to be used with fuseki - attached the correct configuration [config.properties.zip](https://github.com/sepses/cyber-kg-converter/files/4194752/config.properties.zip) )

As you already find out, it will produce the output files (*.ttl) on the output folder.

One note if you want your data to be automatically stored in a fuseki server: I just find out that one of the classes used for Fuseki loading requires oracle-jdk-8 (com.sun.javafx.PlatformUtil).
If someone use openjdk-8 or newer version of java (e.g., java 11), it won’t work at the moment.

- Fajar

**Comment by Radu3000** [comment]
Thank you Fajar!
