### ISSUE TITLE
capec json feed now available

### ISSUE THREAD

**Issue by Radu3000** [sepses/cyber-kg-converter#6]
FYI,

In MITRE beta (aka sub-techiques branch) repo one can find capec feed as JSON at https://github.com/mitre/cti/blob/subtechniques/capec/stix-capec.json

- How does that compare to the xml feed at http://capec.mitre.org/data/xml/views/1000.xml.zip?

Thanks,
Radu

**Comment by kabulkurniawan** [comment]
Hi Radu, 
You can now update the capec resources with the latest version:
 
https://capec.mitre.org/data/archive/capec_latest.zip

Best,
Kabul
